using System.Globalization;
using MathFirst.Domain;

namespace MathFirst.Application;

public sealed class LocalizationService : ILocalizationService
{
    private readonly IPreferenceStore? _preferenceStore;
    private string _persistedPreference = LanguagePreferencePolicy.SystemPreferenceCode;
    private string? _previewLanguage;
    private string? _deviceCultureName;

    public event EventHandler? UiLanguageChanged;

    public LocalizationService(IPreferenceStore? preferenceStore = null, string? initialDeviceCulture = null)
    {
        _preferenceStore = preferenceStore;
        _deviceCultureName = initialDeviceCulture;
        if (_preferenceStore is not null)
        {
            _persistedPreference = _preferenceStore.GetLanguagePreference();
        }
    }

    public string SelectedLanguagePreference => _previewLanguage ?? _persistedPreference;

    public string CurrentUiLanguage
    {
        get
        {
            var active = SelectedLanguagePreference;
            return LanguagePreferencePolicy.Resolve(active, _deviceCultureName ?? CultureInfo.CurrentUICulture.Name);
        }
    }

    public string this[string key] => GetString(key);

    public string this[string key, params object[] args] => GetString(key, args);

    public string GetString(string key, params object[] args)
    {
        var lang = CurrentUiLanguage;
        var dictionary = lang switch
        {
            LanguagePreferencePolicy.GermanLanguageCode => GermanStrings,
            LanguagePreferencePolicy.RussianLanguageCode => RussianStrings,
            _ => EnglishStrings
        };

        if (!dictionary.TryGetValue(key, out var template) && !EnglishStrings.TryGetValue(key, out template))
        {
            template = key;
        }

        if (args is { Length: > 0 })
        {
            try
            {
                return string.Format(CultureInfo.InvariantCulture, template, args);
            }
            catch (FormatException)
            {
                return template;
            }
        }

        return template;
    }

    public void ApplyLanguagePreference(string languagePreference, string? deviceCulture = null)
    {
        var oldLang = CurrentUiLanguage;
        var oldPref = _persistedPreference;
        var hadPreview = _previewLanguage is not null;

        if (deviceCulture is not null)
        {
            _deviceCultureName = deviceCulture;
        }

        _persistedPreference = languagePreference;
        _previewLanguage = null;
        _preferenceStore?.SetLanguagePreference(languagePreference);

        var newLang = CurrentUiLanguage;
        if (hadPreview || !string.Equals(oldPref, languagePreference, StringComparison.OrdinalIgnoreCase) || !string.Equals(oldLang, newLang, StringComparison.OrdinalIgnoreCase))
        {
            UiLanguageChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    public void ApplyPreviewLanguage(string languageCode)
    {
        if (string.Equals(_previewLanguage, languageCode, StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        var oldLang = CurrentUiLanguage;
        _previewLanguage = languageCode;
        var newLang = CurrentUiLanguage;

        if (!string.Equals(oldLang, newLang, StringComparison.OrdinalIgnoreCase) || _previewLanguage is not null)
        {
            UiLanguageChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    public void ClearPreview()
    {
        if (_previewLanguage is not null)
        {
            _previewLanguage = null;
            UiLanguageChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    private static readonly Dictionary<string, string> EnglishStrings = new(StringComparer.Ordinal)
    {
        ["App_Title"] = "MathFirst",
        ["App_Subtitle"] = "Speed and accuracy in mental arithmetic.",
        ["NotFound_Title"] = "Page not found",
        ["NotFound_Description"] = "The requested page could not be found.",
        ["Training_Score"] = "Correct: {0} / {1}",
        ["Training_OperationProgressStage"] = "{0}: Stage {1}",
        ["Training_OperationProgressUnavailable"] = "{0}: progress unavailable",
        ["Training_ProgressStageDisplay"] = "Stage {0}",
        ["Training_OperationProgressGroupAriaLabel"] = "Operation progress",
        ["Training_Correct"] = "Correct!",
        ["Training_Incorrect"] = "Incorrect. The answer is {0}.",
        ["Training_IncorrectTitle"] = "Incorrect",
        ["Training_TimeExpired"] = "Time expired.",
        ["Training_YourAnswer"] = "Your answer: {0}",
        ["Training_CorrectAnswer"] = "Correct answer: {0}",
        ["Training_TimerAriaLabel"] = "Time remaining: {0} seconds",
        ["Training_TimerElapsedAriaLabel"] = "Elapsed response time",
        ["Training_Streak"] = "Streak: {0}",
        ["Training_StreakAriaLabel"] = "Current streak: {0}",
        ["Training_Loading"] = "Loading…",
        ["Training_AnswerInputAriaLabel"] = "Answer input",
        ["Training_EnterNumber"] = "Please enter a number.",
        ["Training_EnterValidNumber"] = "Please enter a valid decimal number.",
        ["Training_ReadyTitle"] = "Ready to practice?",
        ["Training_CurrentProgress"] = "Your progress",
        ["Training_Start"] = "Start",
        ["Training_PausedTitle"] = "Paused",
        ["Training_ResumePractice"] = "Resume practice",
        ["Training_Pause"] = "Pause",
        ["Training_PauseSummaryTitle"] = "Session Summary",
        ["Training_PauseSummaryCompleted"] = "Completed",
        ["Training_PauseSummaryCorrect"] = "Correct",
        ["Training_PauseSummaryStreak"] = "Current streak",
        ["Training_PauseSummaryMedianSpeed"] = "Median correct response time",
        ["Training_PersistenceFailureTitle"] = "Progress could not be saved.",
        ["Training_EvidencePreparationFailureTitle"] = "Next exercise could not be loaded.",
        ["Training_Retry"] = "Retry",
        ["Training_TeachingTitle"] = "Remember this fact",
        ["Training_TeachingExplanation"] = "Notice the equation and correct result before continuing.",
        ["Training_TeachingContinueLocked"] = "Continue ({0} s)",
        ["Training_CheckInTitle"] = "Practice Check-in",
        ["Training_CheckInCorrect"] = "Correct: {0} / {1}",
        ["Training_CheckInCompleted"] = "Problems completed: {0}",
        ["Training_CheckInSpeed"] = "Median correct speed: {0}",
        ["Training_CheckInProgressMade"] = "Progress made",
        ["Training_CheckInProgressChange"] = "{0}: Stage {1} → Stage {2}",
        ["Training_KeepGoing"] = "Keep Going",
        ["Training_TakeBreak"] = "Take a Break",
        ["Training_Unavailable"] = "—",
        ["Training_SettingsAction"] = "Settings",
        ["Common_Back"] = "Back",
        ["Common_Continue"] = "Continue",
        ["Common_Save"] = "Save",
        ["Common_Start"] = "Get Started",
        ["Common_Close"] = "Close",
        ["Common_Cancel"] = "Cancel",
        ["Common_Confirm"] = "Confirm",
        ["Onboarding_WelcomeTitle"] = "Welcome to MathFirst",
        ["Onboarding_Concept"] = "Solve arithmetic facts, answer correctly and quickly, and MathFirst automatically adapts your practice.",
        ["Onboarding_SystemLanguageDetected"] = "Detected system language: {0}",
        ["Onboarding_KeypadTitle"] = "Choose your number keypad",
        ["Onboarding_OperationsTitle"] = "What do you want to practice?",
        ["Onboarding_OperationsDescription"] = "Choose one or more arithmetic operations.",
        ["Onboarding_OperationsMinimum"] = "Keep at least one operation selected.",
        ["Onboarding_TutorialTitle"] = "How MathFirst works",
        ["Onboarding_TutorialStep1Title"] = "Accuracy and Speed",
        ["Onboarding_TutorialStep1Text"] = "Correctness matters most. Answering correctly and quickly helps you progress faster, and available answer time adapts as you practice.",
        ["Onboarding_TutorialStep2Title"] = "Adaptive Repetition",
        ["Onboarding_TutorialStep2Text"] = "Secure facts appear less often, while mistakes and weaker facts return for more practice so you master them reliably.",
        ["Onboarding_TutorialStep3Title"] = "Independent Progress",
        ["Onboarding_TutorialStep3Text"] = "MathFirst guides each operation independently so you strengthen new and challenging facts step by step.",
        ["Onboarding_StepLanguage_Title"] = "Select Language",
        ["Onboarding_StepLanguage_Desc"] = "Choose the language for the MathFirst user interface.",
        ["Onboarding_StepTheme_Title"] = "Select Appearance",
        ["Onboarding_StepTheme_Desc"] = "Choose how MathFirst looks on your screen.",
        ["Onboarding_StepReady_Title"] = "Ready to practice",
        ["Onboarding_StepReady_Desc"] = "Your arithmetic practice is ready. The answer timer starts only when you select Get Started.",
        ["Settings_Title"] = "Settings",
        ["Settings_UILanguage"] = "UI Language",
        ["Settings_UILanguageSystem"] = "System",
        ["Settings_English"] = "English",
        ["Settings_German"] = "Deutsch",
        ["Settings_Russian"] = "Русский",
        ["Settings_Appearance"] = "Appearance",
        ["Settings_AppearanceSystem"] = "System",
        ["Settings_AppearanceLight"] = "Light",
        ["Settings_AppearanceDark"] = "Dark",
        ["Settings_AppearanceChangedTo"] = "Appearance changed to {0}.",
        ["Settings_VersionBuild"] = "Version {0} (Build {1})",
        ["Settings_Build"] = "Build",
        ["Settings_Source"] = "Source",
        ["Settings_CopyDiagnostics"] = "Copy diagnostic info",
        ["Settings_CopyDiagnostics_Success"] = "Diagnostic information copied to clipboard.",
        ["Settings_CopyDiagnostics_Failure"] = "Failed to copy diagnostic information to clipboard.",
        ["Keypad_NumberKeypad"] = "Number keypad",
        ["Keypad_Phone"] = "Phone keypad",
        ["Keypad_Numpad"] = "PC numpad",
        ["Keypad_Explanation"] = "Controls the on-screen number layout shown during MathFirst practice.",
        ["Keypad_Backspace"] = "Backspace",
        ["Keypad_ChangedTo"] = "Number keypad changed to {0}.",
        ["Settings_LanguageChangedTo"] = "Language changed to {0}.",
        ["Settings_HapticFeedbackTitle"] = "Haptic feedback",
        ["Settings_HapticFeedbackHelp"] = "Use vibration feedback for keypad taps and answer results.",
        ["Settings_HapticFeedbackChangedTo"] = "Haptic feedback {0}.",
        ["Common_On"] = "On",
        ["Common_Off"] = "Off",
        ["Settings_PracticeSectionTitle"] = "Practice",
        ["Settings_OperationsTitle"] = "Operations",
        ["Settings_OperationsHelp"] = "Choose which arithmetic operations are included in practice. At least one operation must remain enabled.",
        ["Settings_PracticeTimeTitle"] = "Practice time",
        ["Settings_PracticeTimeHelp"] = "Adjust the answer time available for each exercise.",
        ["PracticeTime_Standard"] = "Standard",
        ["PracticeTime_NoTimePressure"] = "No Time Pressure",
        ["PracticeTime_30s"] = "30 s",
        ["PracticeTime_45s"] = "45 s",
        ["PracticeTime_60s"] = "60 s",
        ["Settings_OperationsChanged"] = "Practice operations updated.",
        ["Settings_PracticeConfigurationFailed"] = "Practice could not be updated. Your operation choice was saved. Retry before returning to practice.",
        ["Settings_SaveFailed"] = "Setting could not be saved.",
        ["Settings_PracticeTimeChangedTo"] = "Practice time changed to {0}.",
        ["Operation_Addition"] = "Addition",
        ["Operation_Subtraction"] = "Subtraction",
        ["Operation_Multiplication"] = "Multiplication",
        ["Operation_Division"] = "Division",
        ["Diagnostics_Group_Learning"] = "Operation Bands",
        ["DangerZone_Title"] = "Danger Zone",
        ["DangerZone_Desc"] = "Manage learning progress and preferences stored on this device.",
        ["Reset_LearningProgress_Title"] = "Reset Learning Progress",
        ["Reset_LearningProgress_Desc"] = "Clears learning state and attempt history. Language, appearance, and onboarding remain unchanged.",
        ["Reset_LearningProgress_Confirm"] = "Are you sure you want to clear all learning progress?",
        ["Reset_LearningProgress_Success"] = "Learning progress has been cleared and starts over.",
        ["Reset_UiPreferences_Title"] = "Restore Default Settings",
        ["Reset_UiPreferences_Desc"] = "Restores language and appearance to System, the number keypad to PC numpad, and requires onboarding again. Learning progress is preserved.",
        ["Reset_UiPreferences_Confirm"] = "Restore default settings and show onboarding again? Your learning progress will remain intact.",
        ["Reset_UiPreferences_Action"] = "Restore Defaults",
        ["Reset_UiPreferences_Success"] = "Default settings have been restored.",
        ["Reset_FullLocal_Title"] = "Reset All Application Data",
        ["Reset_FullLocal_Desc"] = "Resets learner data, onboarding, language, appearance, and number keypad to a fresh installation state.",
        ["Reset_FullLocal_Confirm"] = "Reset all learner data and settings? This action cannot be undone.",
        ["Reset_FullLocal_Action"] = "Reset Data",
        ["Reset_FullLocal_Success"] = "Full reset complete. Application returned to fresh install state.",
        ["Settings_Privacy"] = "Privacy",
        ["Settings_Privacy_Desc"] = "MathFirst operates entirely offline on this device without accounts, analytics, or remote data collection.",
        ["Settings_Privacy_Action"] = "View Privacy Policy",
        ["Privacy_Title"] = "Privacy",
        ["Privacy_Overview_Title"] = "Overview",
        ["Privacy_Overview_Body"] = "MathFirst is designed to protect learner privacy by operating locally on your device without user accounts, advertising, analytics, or remote data collection.",
        ["Privacy_NoCollection_Title"] = "No Remote Collection or Sharing",
        ["Privacy_NoCollection_Body"] = "MathFirst does not collect personal data, does not transmit learner data to the developer, does not use advertising or tracking, and does not sell or share user data with third parties.",
        ["Privacy_LocalStorage_Title"] = "Local Storage and Device Transfer",
        ["Privacy_LocalStorage_Body"] = "Learning progress and preferences are stored only on this device. On supported Android versions, direct device-to-device migration through the operating system may transfer the local learner database without sending data to MathFirst.",
        ["Privacy_Delete_Title"] = "Removing Local Data",
        ["Privacy_Delete_Body"] = "You can remove locally stored learner data and preferences at any time using the reset options in Settings or by uninstalling the application.",
        ["Privacy_Contact_Title"] = "Contact",
        ["Privacy_Contact_Body"] = "Privacy questions can be submitted through the public MathFirst GitHub Issues page:",
        ["CyberDefense_Title"] = "Cyber Defense",
        ["CyberDefense_ShieldLabel"] = "Shield integrity",
        ["CyberDefense_EnemyHpLabel"] = "Opponent integrity",
        ["CyberDefense_ShieldDisplay"] = "Shield: {0} / {1}",
        ["CyberDefense_HpDisplay"] = "HP: {0} / {1}",
        ["CyberDefense_Opponent_GlitchDrone"] = "Glitch Drone",
        ["CyberDefense_Opponent_VirusCore"] = "Virus Core",
        ["CyberDefense_Opponent_CrystalMalware"] = "Crystal Malware",
        ["CyberDefense_Header_Subtitle"] = "PRACTICE > PROGRESS > STRONGER MINDS",
        ["CyberDefense_WaveDisplay"] = "WAVE {0} / {1}",
        ["CyberDefense_YourShield"] = "YOUR SHIELD",
        ["CyberDefense_Integrity"] = "Integrity",
        ["CyberDefense_SolveToAttack"] = "SOLVE TO ATTACK",
        ["CyberDefense_OperationsTitle"] = "OPERATIONS",
        ["CyberDefense_Telemetry_Solve"] = "SOLVE PROBLEMS",
        ["CyberDefense_Telemetry_Defend"] = "DEFEND SHIELD",
        ["CyberDefense_Telemetry_Progress"] = "YOUR PROGRESS",
        ["CyberDefense_Opponent_GlitchDrone_Desc"] = "A corrupted drone disrupting the learning network.",
        ["CyberDefense_Opponent_VirusCore_Desc"] = "A rogue core multiplying across calculation buffers.",
        ["CyberDefense_Opponent_CrystalMalware_Desc"] = "A crystallized threat attempting to lock numeric flows.",
        ["CyberDefense_Combo"] = "COMBO ×{0}",
        ["CyberDefense_ComboAriaLabel"] = "Current combo: {0}",
        ["CyberDefense_Feedback_Hit"] = "-1",
        ["CyberDefense_Feedback_Blocked"] = "BLOCKED",
        ["CyberDefense_Opponent_DataLeech"] = "Data Leech",
        ["CyberDefense_Opponent_DataLeech_Desc"] = "A siphon entity draining calculation buffers.",
        ["CyberDefense_Opponent_FirewallBreaker"] = "Firewall Breaker",
        ["CyberDefense_Opponent_FirewallBreaker_Desc"] = "Heavy armored brute force battering through system gates.",
        ["CyberDefense_Opponent_SignalPhantom"] = "Signal Phantom",
        ["CyberDefense_Opponent_SignalPhantom_Desc"] = "Phase-shifting stealth anomaly glitching through frequency bands.",
        ["CyberDefense_Opponent_QuantumBug"] = "Quantum Bug",
        ["CyberDefense_Opponent_QuantumBug_Desc"] = "Multithreaded subatomic parasite multiplying across memory sectors.",
        ["CyberDefense_Opponent_TrojanWasp"] = "Trojan Wasp",
        ["CyberDefense_Opponent_TrojanWasp_Desc"] = "High-speed interceptor injecting malicious payloads.",
        ["CyberDefense_Opponent_NexusOverlord"] = "Nexus Overlord",
        ["CyberDefense_Opponent_NexusOverlord_Desc"] = "Central mainframe security titan with multi-layer adaptive shielding.",
        ["CyberDefense_Feedback_CriticalHit"] = "CRITICAL HIT",
        ["CyberDefense_BossLabel"] = "BOSS",
        ["CyberDefense_BossBattle"] = "BOSS BATTLE"
    };

    private static readonly Dictionary<string, string> GermanStrings = new(StringComparer.Ordinal)
    {
        ["App_Title"] = "MathFirst",
        ["App_Subtitle"] = "Schnelligkeit und Sicherheit beim Kopfrechnen.",
        ["NotFound_Title"] = "Seite nicht gefunden",
        ["NotFound_Description"] = "Die angeforderte Seite wurde nicht gefunden.",
        ["Training_Score"] = "Richtig: {0} / {1}",
        ["Training_OperationProgressStage"] = "{0}: Stufe {1}",
        ["Training_OperationProgressUnavailable"] = "{0}: Fortschritt nicht verfügbar",
        ["Training_ProgressStageDisplay"] = "Stufe {0}",
        ["Training_OperationProgressGroupAriaLabel"] = "Fortschritt nach Rechenarten",
        ["Training_Correct"] = "Richtig!",
        ["Training_Incorrect"] = "Falsch. Das Ergebnis ist {0}.",
        ["Training_IncorrectTitle"] = "Falsch",
        ["Training_TimeExpired"] = "Zeit abgelaufen.",
        ["Training_YourAnswer"] = "Deine Antwort: {0}",
        ["Training_CorrectAnswer"] = "Richtige Antwort: {0}",
        ["Training_TimerAriaLabel"] = "Verbleibende Zeit: {0} Sekunden",
        ["Training_TimerElapsedAriaLabel"] = "Verstrichene Antwortzeit",
        ["Training_Streak"] = "Serie: {0}",
        ["Training_StreakAriaLabel"] = "Aktuelle Serie: {0}",
        ["Training_Loading"] = "Wird geladen…",
        ["Training_AnswerInputAriaLabel"] = "Antwortfeld",
        ["Training_EnterNumber"] = "Bitte eine Zahl eingeben.",
        ["Training_EnterValidNumber"] = "Bitte eine gültige Dezimalzahl eingeben.",
        ["Training_ReadyTitle"] = "Bereit zum Üben?",
        ["Training_CurrentProgress"] = "Dein Fortschritt",
        ["Training_Start"] = "Los geht's",
        ["Training_PausedTitle"] = "Pausiert",
        ["Training_ResumePractice"] = "Weiterüben",
        ["Training_Pause"] = "Pausieren",
        ["Training_PauseSummaryTitle"] = "Sitzungsübersicht",
        ["Training_PauseSummaryCompleted"] = "Abgeschlossen",
        ["Training_PauseSummaryCorrect"] = "Richtig",
        ["Training_PauseSummaryStreak"] = "Aktuelle Serie",
        ["Training_PauseSummaryMedianSpeed"] = "Mittlere Antwortzeit (richtig)",
        ["Training_PersistenceFailureTitle"] = "Fortschritt konnte nicht gespeichert werden.",
        ["Training_EvidencePreparationFailureTitle"] = "Nächste Aufgabe konnte nicht geladen werden.",
        ["Training_Retry"] = "Erneut versuchen",
        ["Training_TeachingTitle"] = "Merke dir diese Aufgabe",
        ["Training_TeachingExplanation"] = "Präge dir die Gleichung und das richtige Ergebnis ein, bevor du weitermachst.",
        ["Training_TeachingContinueLocked"] = "Weiter ({0} s)",
        ["Training_CheckInTitle"] = "Übungs-Zwischenstand",
        ["Training_CheckInCorrect"] = "Richtig: {0} / {1}",
        ["Training_CheckInCompleted"] = "Gelöste Aufgaben: {0}",
        ["Training_CheckInSpeed"] = "Mittlere Zeit (richtig): {0}",
        ["Training_CheckInProgressMade"] = "Fortschritt",
        ["Training_CheckInProgressChange"] = "{0}: Stufe {1} → Stufe {2}",
        ["Training_KeepGoing"] = "Weiterüben",
        ["Training_TakeBreak"] = "Pause machen",
        ["Training_Unavailable"] = "—",
        ["Training_SettingsAction"] = "Einstellungen",
        ["Common_Back"] = "Zurück",
        ["Common_Continue"] = "Weiter",
        ["Common_Save"] = "Speichern",
        ["Common_Start"] = "Los geht's",
        ["Common_Close"] = "Schließen",
        ["Common_Cancel"] = "Abbrechen",
        ["Common_Confirm"] = "Bestätigen",
        ["Onboarding_WelcomeTitle"] = "Willkommen bei MathFirst",
        ["Onboarding_Concept"] = "Löse Rechenaufgaben richtig und schnell – MathFirst passt dein Training automatisch an.",
        ["Onboarding_SystemLanguageDetected"] = "Erkannte Systemsprache: {0}",
        ["Onboarding_KeypadTitle"] = "Zahlentastatur auswählen",
        ["Onboarding_OperationsTitle"] = "Was möchtest du üben?",
        ["Onboarding_OperationsDescription"] = "Wähle eine oder mehrere Rechenarten.",
        ["Onboarding_OperationsMinimum"] = "Mindestens eine Rechenart muss ausgewählt bleiben.",
        ["Onboarding_TutorialTitle"] = "So funktioniert MathFirst",
        ["Onboarding_TutorialStep1Title"] = "Genauigkeit und Tempo",
        ["Onboarding_TutorialStep1Text"] = "Richtigkeit steht an erster Stelle. Richtiges und zügiges Antworten hilft dir, schneller voranzukommen, und die verfügbare Antwortzeit passt sich beim Üben an.",
        ["Onboarding_TutorialStep2Title"] = "Angepasste Wiederholung",
        ["Onboarding_TutorialStep2Text"] = "Sichere Aufgaben erscheinen seltener, während Fehler und unsichere Aufgaben für mehr Übung zurückkehren, damit du sie zuverlässig meisterst.",
        ["Onboarding_TutorialStep3Title"] = "Unabhängiger Fortschritt",
        ["Onboarding_TutorialStep3Text"] = "MathFirst führt jede Rechenart unabhängig, damit du neue und anspruchsvolle Aufgaben Schritt für Schritt festigst.",
        ["Onboarding_StepLanguage_Title"] = "Sprache auswählen",
        ["Onboarding_StepLanguage_Desc"] = "Wähle die Sprache für die MathFirst-Benutzeroberfläche.",
        ["Onboarding_StepTheme_Title"] = "Erscheinungsbild auswählen",
        ["Onboarding_StepTheme_Desc"] = "Wähle, wie MathFirst auf deinem Bildschirm dargestellt wird.",
        ["Onboarding_StepReady_Title"] = "Bereit zum Üben",
        ["Onboarding_StepReady_Desc"] = "Dein Rechentraining ist bereit. Der Antworttimer startet erst mit „Los geht's“.",
        ["Settings_Title"] = "Einstellungen",
        ["Settings_UILanguage"] = "Sprache",
        ["Settings_UILanguageSystem"] = "System",
        ["Settings_English"] = "English",
        ["Settings_German"] = "Deutsch",
        ["Settings_Russian"] = "Русский",
        ["Settings_Appearance"] = "Erscheinungsbild",
        ["Settings_AppearanceSystem"] = "System",
        ["Settings_AppearanceLight"] = "Hell",
        ["Settings_AppearanceDark"] = "Dunkel",
        ["Settings_AppearanceChangedTo"] = "Erscheinungsbild geändert auf {0}.",
        ["Settings_VersionBuild"] = "Version {0} (Build {1})",
        ["Settings_Build"] = "Build",
        ["Settings_Source"] = "Quelle",
        ["Settings_CopyDiagnostics"] = "Diagnose-Informationen kopieren",
        ["Settings_CopyDiagnostics_Success"] = "Diagnose-Informationen wurden in die Zwischenablage kopiert.",
        ["Settings_CopyDiagnostics_Failure"] = "Diagnose-Informationen konnten nicht kopiert werden.",
        ["Keypad_NumberKeypad"] = "Zahlentastatur",
        ["Keypad_Phone"] = "Telefon-Tastatur",
        ["Keypad_Numpad"] = "PC-Ziffernblock",
        ["Keypad_Explanation"] = "Legt die Bildschirm-Zahlenanordnung für das Training mit MathFirst fest.",
        ["Keypad_Backspace"] = "Rücktaste",
        ["Keypad_ChangedTo"] = "Zahlentastatur geändert auf {0}.",
        ["Settings_LanguageChangedTo"] = "Sprache geändert auf {0}.",
        ["Settings_HapticFeedbackTitle"] = "Haptisches Feedback",
        ["Settings_HapticFeedbackHelp"] = "Vibrationsfeedback für Tastatureingaben und Antwort-Ergebnisse verwenden.",
        ["Settings_HapticFeedbackChangedTo"] = "Haptisches Feedback {0}.",
        ["Common_On"] = "Ein",
        ["Common_Off"] = "Aus",
        ["Settings_PracticeSectionTitle"] = "Training",
        ["Settings_OperationsTitle"] = "Rechenarten",
        ["Settings_OperationsHelp"] = "Wähle, welche Rechenarten im Training vorkommen. Mindestens eine Rechenart muss aktiv bleiben.",
        ["Settings_PracticeTimeTitle"] = "Übungszeit",
        ["Settings_PracticeTimeHelp"] = "Passe die verfügbare Antwortzeit für jede Aufgabe an.",
        ["PracticeTime_Standard"] = "Standard",
        ["PracticeTime_NoTimePressure"] = "Ohne Zeitdruck",
        ["PracticeTime_30s"] = "30 s",
        ["PracticeTime_45s"] = "45 s",
        ["PracticeTime_60s"] = "60 s",
        ["Settings_OperationsChanged"] = "Rechenarten für das Training aktualisiert.",
        ["Settings_PracticeConfigurationFailed"] = "Das Training konnte nicht aktualisiert werden. Deine Rechenart-Auswahl wurde gespeichert. Versuche es erneut, bevor du zum Training zurückkehrst.",
        ["Settings_SaveFailed"] = "Einstellung konnte nicht gespeichert werden.",
        ["Settings_PracticeTimeChangedTo"] = "Übungszeit geändert auf {0}.",
        ["Operation_Addition"] = "Addition",
        ["Operation_Subtraction"] = "Subtraktion",
        ["Operation_Multiplication"] = "Multiplikation",
        ["Operation_Division"] = "Division",
        ["Diagnostics_Group_Learning"] = "Operationsbänder",
        ["DangerZone_Title"] = "Gefahrenbereich",
        ["DangerZone_Desc"] = "Verwalte Lernfortschritt und Einstellungen auf diesem Gerät.",
        ["Reset_LearningProgress_Title"] = "Lernfortschritt zurücksetzen",
        ["Reset_LearningProgress_Desc"] = "Löscht Lernstand und Versuchshistorie. Sprache, Erscheinungsbild und Onboarding bleiben erhalten.",
        ["Reset_LearningProgress_Confirm"] = "Möchtest du den gesamten Lernfortschritt wirklich löschen?",
        ["Reset_LearningProgress_Success"] = "Der Lernfortschritt wurde gelöscht und beginnt von vorn.",
        ["Reset_UiPreferences_Title"] = "Standardeinstellungen wiederherstellen",
        ["Reset_UiPreferences_Desc"] = "Stellt Sprache und Erscheinungsbild auf System sowie die Zahlentastatur auf PC-Ziffernblock zurück und macht das Onboarding erneut erforderlich. Der Lernfortschritt bleibt erhalten.",
        ["Reset_UiPreferences_Confirm"] = "Standardeinstellungen wiederherstellen und das Onboarding erneut anzeigen? Dein Lernfortschritt bleibt erhalten.",
        ["Reset_UiPreferences_Action"] = "Standards wiederherstellen",
        ["Reset_UiPreferences_Success"] = "Standardeinstellungen wurden wiederhergestellt.",
        ["Reset_FullLocal_Title"] = "Alle Anwendungsdaten zurücksetzen",
        ["Reset_FullLocal_Desc"] = "Setzt Lerndaten, Onboarding, Sprache, Erscheinungsbild und Zahlentastatur auf den Zustand einer Neuinstallation zurück.",
        ["Reset_FullLocal_Confirm"] = "Alle Lerndaten und Einstellungen zurücksetzen? Diese Aktion kann nicht rückgängig gemacht werden.",
        ["Reset_FullLocal_Action"] = "Daten zurücksetzen",
        ["Reset_FullLocal_Success"] = "Vollständiger Reset abgeschlossen. App befindet sich im Zustand der Neuinstallation.",
        ["Settings_Privacy"] = "Datenschutz",
        ["Settings_Privacy_Desc"] = "MathFirst arbeitet vollständig offline auf diesem Gerät ohne Konten, Analysen oder Datenerfassung.",
        ["Settings_Privacy_Action"] = "Datenschutzerklärung anzeigen",
        ["Privacy_Title"] = "Datenschutz",
        ["Privacy_Overview_Title"] = "Übersicht",
        ["Privacy_Overview_Body"] = "MathFirst schützt die Privatsphäre der Lernenden und arbeitet lokal auf deinem Gerät ohne Benutzerkonten, Werbung, Analysen oder Datenübertragung.",
        ["Privacy_NoCollection_Title"] = "Keine Datenerfassung oder Weitergabe",
        ["Privacy_NoCollection_Body"] = "MathFirst erfasst keine personenbezogenen Daten, überträgt keine Lerndaten an die Entwickler, nutzt weder Werbung noch Tracking und verkauft oder teilt keine Daten mit Dritten.",
        ["Privacy_LocalStorage_Title"] = "Lokale Speicherung und Geräteübertragung",
        ["Privacy_LocalStorage_Body"] = "Lernfortschritt und Einstellungen werden ausschließlich lokal auf diesem Gerät gespeichert. Bei einer direkten Geräteübertragung über Android kann die lokale Lerndatenbank ohne Beteiligung von MathFirst übertragen werden.",
        ["Privacy_Delete_Title"] = "Daten löschen",
        ["Privacy_Delete_Body"] = "Du kannst lokal gespeicherte Lerndaten und Einstellungen jederzeit über die Optionen in den Einstellungen oder durch Deinstallieren der App löschen.",
        ["Privacy_Contact_Title"] = "Kontakt",
        ["Privacy_Contact_Body"] = "Fragen zum Datenschutz können über die öffentliche GitHub-Issues-Seite von MathFirst gestellt werden:",
        ["CyberDefense_Title"] = "Cyber-Abwehr",
        ["CyberDefense_ShieldLabel"] = "Schildintegrität",
        ["CyberDefense_EnemyHpLabel"] = "Gegnerintegrität",
        ["CyberDefense_ShieldDisplay"] = "Schild: {0} / {1}",
        ["CyberDefense_HpDisplay"] = "KP: {0} / {1}",
        ["CyberDefense_Opponent_GlitchDrone"] = "Glitch-Drohne",
        ["CyberDefense_Opponent_VirusCore"] = "Virus-Kern",
        ["CyberDefense_Opponent_CrystalMalware"] = "Kristall-Malware",
        ["CyberDefense_Header_Subtitle"] = "TRAINING > FORTSCHRITT > STÄRKERER GEIST",
        ["CyberDefense_WaveDisplay"] = "WELLE {0} / {1}",
        ["CyberDefense_YourShield"] = "DEIN SCHILD",
        ["CyberDefense_Integrity"] = "Integrität",
        ["CyberDefense_SolveToAttack"] = "LÖSEN ZUM ANGRIFF",
        ["CyberDefense_OperationsTitle"] = "RECHENARTEN",
        ["CyberDefense_Telemetry_Solve"] = "AUFGABEN LÖSEN",
        ["CyberDefense_Telemetry_Defend"] = "SCHILD VERTEIDIGEN",
        ["CyberDefense_Telemetry_Progress"] = "DEIN FORTSCHRITT",
        ["CyberDefense_Opponent_GlitchDrone_Desc"] = "Eine fehlerhafte Drohne, die das Lernnetzwerk stört.",
        ["CyberDefense_Opponent_VirusCore_Desc"] = "Ein bösartiger Kern, der Rechenpuffer infiziert.",
        ["CyberDefense_Opponent_CrystalMalware_Desc"] = "Ein kristallines Konstrukt, das Zahlenknoten blockiert.",
        ["CyberDefense_Combo"] = "KOMBO ×{0}",
        ["CyberDefense_ComboAriaLabel"] = "Aktuelle Kombo: {0}",
        ["CyberDefense_Feedback_Hit"] = "-1",
        ["CyberDefense_Feedback_Blocked"] = "BLOCKIERT",
        ["CyberDefense_Opponent_DataLeech"] = "Daten-Egel",
        ["CyberDefense_Opponent_DataLeech_Desc"] = "Ein Siphon-Konstrukt, das Rechenpuffer leersaugt.",
        ["CyberDefense_Opponent_FirewallBreaker"] = "Firewall-Brecher",
        ["CyberDefense_Opponent_FirewallBreaker_Desc"] = "Gepanzerte Brute-Force-Einheit, die Systemtore rammt.",
        ["CyberDefense_Opponent_SignalPhantom"] = "Signal-Phantom",
        ["CyberDefense_Opponent_SignalPhantom_Desc"] = "Phasenverschobene Stealth-Anomalie im Frequenzspektrum.",
        ["CyberDefense_Opponent_QuantumBug"] = "Quanten-Bug",
        ["CyberDefense_Opponent_QuantumBug_Desc"] = "Subatomarer Parasit, der Speichersektoren belegt.",
        ["CyberDefense_Opponent_TrojanWasp"] = "Trojaner-Wespe",
        ["CyberDefense_Opponent_TrojanWasp_Desc"] = "Hochgeschwindigkeits-Abfangjäger mit Schadcode-Stachel.",
        ["CyberDefense_Opponent_NexusOverlord"] = "Nexus-Overlord",
        ["CyberDefense_Opponent_NexusOverlord_Desc"] = "Zentraler Mainframe-Sicherheits-Titan mit adaptiver Mehrschichtpanzerung.",
        ["CyberDefense_Feedback_CriticalHit"] = "KRITISCH!",
        ["CyberDefense_BossLabel"] = "BOSS",
        ["CyberDefense_BossBattle"] = "BOSS-KAMPF"
    };

    private static readonly Dictionary<string, string> RussianStrings = new(StringComparer.Ordinal)
    {
        ["App_Title"] = "MathFirst",
        ["App_Subtitle"] = "Скорость и точность устного счета.",
        ["NotFound_Title"] = "Страница не найдена",
        ["NotFound_Description"] = "Запрошенная страница не найдена.",
        ["Training_Score"] = "Правильно: {0} / {1}",
        ["Training_OperationProgressStage"] = "{0}: уровень {1}",
        ["Training_OperationProgressUnavailable"] = "{0}: прогресс недоступен",
        ["Training_ProgressStageDisplay"] = "Уровень {0}",
        ["Training_OperationProgressGroupAriaLabel"] = "Прогресс по операциям",
        ["Training_Correct"] = "Правильно!",
        ["Training_Incorrect"] = "Неверно. Правильный ответ: {0}.",
        ["Training_IncorrectTitle"] = "Неверно",
        ["Training_TimeExpired"] = "Время вышло.",
        ["Training_YourAnswer"] = "Твой ответ: {0}",
        ["Training_CorrectAnswer"] = "Правильный ответ: {0}",
        ["Training_TimerAriaLabel"] = "Оставшееся время: {0} сек.",
        ["Training_TimerElapsedAriaLabel"] = "Прошедшее время ответа",
        ["Training_Streak"] = "Серия: {0}",
        ["Training_StreakAriaLabel"] = "Текущая серия: {0}",
        ["Training_Loading"] = "Загрузка…",
        ["Training_AnswerInputAriaLabel"] = "Поле ответа",
        ["Training_EnterNumber"] = "Пожалуйста, введите число.",
        ["Training_EnterValidNumber"] = "Пожалуйста, введите допустимое десятичное число.",
        ["Training_ReadyTitle"] = "Пора заниматься?",
        ["Training_CurrentProgress"] = "Ваш прогресс",
        ["Training_Start"] = "Начать",
        ["Training_PausedTitle"] = "Пауза",
        ["Training_ResumePractice"] = "Продолжить занятие",
        ["Training_Pause"] = "Приостановить",
        ["Training_PauseSummaryTitle"] = "Итоги сессии",
        ["Training_PauseSummaryCompleted"] = "Завершено",
        ["Training_PauseSummaryCorrect"] = "Правильно",
        ["Training_PauseSummaryStreak"] = "Текущая серия",
        ["Training_PauseSummaryMedianSpeed"] = "Медианное время ответа (верно)",
        ["Training_PersistenceFailureTitle"] = "Не удалось сохранить прогресс.",
        ["Training_EvidencePreparationFailureTitle"] = "Не удалось загрузить следующее упражнение.",
        ["Training_Retry"] = "Повторить",
        ["Training_TeachingTitle"] = "Запомни этот пример",
        ["Training_TeachingExplanation"] = "Обрати внимание на пример и правильный ответ перед продолжением.",
        ["Training_TeachingContinueLocked"] = "Продолжить ({0} сек.)",
        ["Training_CheckInTitle"] = "Промежуточный итог",
        ["Training_CheckInCorrect"] = "Правильно: {0} / {1}",
        ["Training_CheckInCompleted"] = "Решено примеров: {0}",
        ["Training_CheckInSpeed"] = "Медианное время (верно): {0}",
        ["Training_CheckInProgressMade"] = "Прогресс",
        ["Training_CheckInProgressChange"] = "{0}: этап {1} → этап {2}",
        ["Training_KeepGoing"] = "Продолжить",
        ["Training_TakeBreak"] = "Сделать перерыв",
        ["Training_Unavailable"] = "—",
        ["Training_SettingsAction"] = "Настройки",
        ["Common_Back"] = "Назад",
        ["Common_Continue"] = "Продолжить",
        ["Common_Save"] = "Сохранить",
        ["Common_Start"] = "Начать",
        ["Common_Close"] = "Закрыть",
        ["Common_Cancel"] = "Отмена",
        ["Common_Confirm"] = "Подтвердить",
        ["Onboarding_WelcomeTitle"] = "Добро пожаловать в MathFirst",
        ["Onboarding_Concept"] = "Решайте примеры правильно и быстро — MathFirst автоматически адаптирует тренировку.",
        ["Onboarding_SystemLanguageDetected"] = "Определённый язык системы: {0}",
        ["Onboarding_KeypadTitle"] = "Выберите цифровую клавиатуру",
        ["Onboarding_OperationsTitle"] = "Что вы хотите тренировать?",
        ["Onboarding_OperationsDescription"] = "Выберите одну или несколько арифметических операций.",
        ["Onboarding_OperationsMinimum"] = "Должна оставаться выбранной хотя бы одна операция.",
        ["Onboarding_TutorialTitle"] = "Как работает MathFirst",
        ["Onboarding_TutorialStep1Title"] = "Точность и темп",
        ["Onboarding_TutorialStep1Text"] = "Правильность важнее всего. Правильные и быстрые ответы помогают продвигаться быстрее, а доступное время на ответ адаптируется по ходу тренировки.",
        ["Onboarding_TutorialStep2Title"] = "Адаптивное повторение",
        ["Onboarding_TutorialStep2Text"] = "Хорошо усвоенные примеры появляются реже, а ошибки и сложные примеры возвращаются для дополнительной тренировки, пока не закрепятся.",
        ["Onboarding_TutorialStep3Title"] = "Независимый прогресс",
        ["Onboarding_TutorialStep3Text"] = "MathFirst развивает каждую операцию независимо, помогая шаг за шагом осваивать новые и сложные примеры.",
        ["Onboarding_StepLanguage_Title"] = "Выберите язык",
        ["Onboarding_StepLanguage_Desc"] = "Выберите язык интерфейса MathFirst.",
        ["Onboarding_StepTheme_Title"] = "Оформление",
        ["Onboarding_StepTheme_Desc"] = "Выберите тему оформления MathFirst.",
        ["Onboarding_StepReady_Title"] = "Всё готово",
        ["Onboarding_StepReady_Desc"] = "Тренировка по арифметике готова. Таймер ответа запустится только после нажатия «Начать».",
        ["Settings_Title"] = "Настройки",
        ["Settings_UILanguage"] = "Язык интерфейса",
        ["Settings_UILanguageSystem"] = "Системный",
        ["Settings_English"] = "English",
        ["Settings_German"] = "Deutsch",
        ["Settings_Russian"] = "Русский",
        ["Settings_Appearance"] = "Оформление",
        ["Settings_AppearanceSystem"] = "Системная",
        ["Settings_AppearanceLight"] = "Светлая",
        ["Settings_AppearanceDark"] = "Темная",
        ["Settings_AppearanceChangedTo"] = "Тема изменена на: {0}.",
        ["Settings_VersionBuild"] = "Версия {0} (сборка {1})",
        ["Settings_Build"] = "Сборка",
        ["Settings_Source"] = "Источник",
        ["Settings_CopyDiagnostics"] = "Скопировать данные диагностики",
        ["Settings_CopyDiagnostics_Success"] = "Данные диагностики скопированы в буфер обмена.",
        ["Settings_CopyDiagnostics_Failure"] = "Не удалось скопировать данные диагностики.",
        ["Keypad_NumberKeypad"] = "Цифровая клавиатура",
        ["Keypad_Phone"] = "Телефонная клавиатура",
        ["Keypad_Numpad"] = "Цифровой блок ПК",
        ["Keypad_Explanation"] = "Определяет расположение экранных цифр во время тренировки MathFirst.",
        ["Keypad_Backspace"] = "Удалить символ",
        ["Keypad_ChangedTo"] = "Цифровая клавиатура изменена на: {0}.",
        ["Settings_LanguageChangedTo"] = "Язык изменен на: {0}.",
        ["Settings_HapticFeedbackTitle"] = "Тактильный отклик",
        ["Settings_HapticFeedbackHelp"] = "Использовать вибрацию при нажатии клавиш и результатах ответов.",
        ["Settings_HapticFeedbackChangedTo"] = "Тактильный отклик: {0}",
        ["Common_On"] = "Вкл.",
        ["Common_Off"] = "Выкл.",
        ["Settings_PracticeSectionTitle"] = "Тренировка",
        ["Settings_OperationsTitle"] = "Арифметические действия",
        ["Settings_OperationsHelp"] = "Выберите действия для тренировки. Хотя бы одно действие должно оставаться включенным.",
        ["Settings_PracticeTimeTitle"] = "Время на ответ",
        ["Settings_PracticeTimeHelp"] = "Настройте доступное время для каждого примера.",
        ["PracticeTime_Standard"] = "Стандарт",
        ["PracticeTime_NoTimePressure"] = "Без спешки",
        ["PracticeTime_30s"] = "30 сек.",
        ["PracticeTime_45s"] = "45 сек.",
        ["PracticeTime_60s"] = "60 сек.",
        ["Settings_OperationsChanged"] = "Выбранные действия обновлены.",
        ["Settings_PracticeConfigurationFailed"] = "Не удалось обновить тренировку. Выбор арифметических действий сохранён. Повторите попытку перед возвращением к тренировке.",
        ["Settings_SaveFailed"] = "Не удалось сохранить настройку.",
        ["Settings_PracticeTimeChangedTo"] = "Время на ответ изменено на {0}.",
        ["Operation_Addition"] = "Сложение",
        ["Operation_Subtraction"] = "Вычитание",
        ["Operation_Multiplication"] = "Умножение",
        ["Operation_Division"] = "Деление",
        ["Diagnostics_Group_Learning"] = "Прогресс по операциям",
        ["DangerZone_Title"] = "Опасная зона",
        ["DangerZone_Desc"] = "Действия по сбросу прогресса обучения и настроек устройства.",
        ["Reset_LearningProgress_Title"] = "Сбросить прогресс обучения",
        ["Reset_LearningProgress_Desc"] = "Очищает состояние обучения и историю попыток. Язык, оформление и онбординг сохраняются.",
        ["Reset_LearningProgress_Confirm"] = "Очистить весь прогресс обучения?",
        ["Reset_LearningProgress_Success"] = "Прогресс обучения очищен и начинается заново.",
        ["Reset_UiPreferences_Title"] = "Восстановить настройки по умолчанию",
        ["Reset_UiPreferences_Desc"] = "Возвращает язык и оформление к системным значениям, выбирает цифровой блок ПК и снова требует пройти онбординг. Прогресс обучения сохраняется.",
        ["Reset_UiPreferences_Confirm"] = "Восстановить настройки по умолчанию и снова показать онбординг? Прогресс обучения сохранится.",
        ["Reset_UiPreferences_Action"] = "Восстановить настройки",
        ["Reset_UiPreferences_Success"] = "Настройки по умолчанию восстановлены.",
        ["Reset_FullLocal_Title"] = "Сбросить все данные приложения",
        ["Reset_FullLocal_Desc"] = "Сбрасывает данные обучения, онбординг, язык, оформление и цифровую клавиатуру до состояния новой установки.",
        ["Reset_FullLocal_Confirm"] = "Сбросить все данные обучения и настройки? Это действие нельзя отменить.",
        ["Reset_FullLocal_Action"] = "Сбросить данные",
        ["Reset_FullLocal_Success"] = "Полный сброс выполнен. Приложение возвращено в исходное состояние.",
        ["Settings_Privacy"] = "Конфиденциальность",
        ["Settings_Privacy_Desc"] = "MathFirst работает полностью автономно на этом устройстве без учетных записей, аналитики и сбора данных.",
        ["Settings_Privacy_Action"] = "Политика конфиденциальности",
        ["Privacy_Title"] = "Конфиденциальность",
        ["Privacy_Overview_Title"] = "Обзор",
        ["Privacy_Overview_Body"] = "MathFirst защищает конфиденциальность и работает локально на вашем устройстве без учетных записей, рекламы, аналитики и передачи данных.",
        ["Privacy_NoCollection_Title"] = "Без сбора данных и передачи третьим лицам",
        ["Privacy_NoCollection_Body"] = "MathFirst не собирает персональные данные, не отправляет данные разработчику, не использует рекламу или трекинг и не передает данные третьим лицам.",
        ["Privacy_LocalStorage_Title"] = "Локальное хранение и перенос между устройствами",
        ["Privacy_LocalStorage_Body"] = "Прогресс обучения и настройки хранятся только на этом устройстве. При прямом переносе между устройствами через Android локальная база данных может переноситься без участия MathFirst.",
        ["Privacy_Delete_Title"] = "Удаление данных",
        ["Privacy_Delete_Body"] = "Вы можете удалить сохраненные данные обучения и настройки в любой момент через меню настроек или удалив приложение.",
        ["Privacy_Contact_Title"] = "Контакты",
        ["Privacy_Contact_Body"] = "Вопросы о конфиденциальности можно отправить через страницу Issues проекта MathFirst на GitHub:",
        ["CyberDefense_Title"] = "Киберзащита",
        ["CyberDefense_ShieldLabel"] = "Прочность щита",
        ["CyberDefense_EnemyHpLabel"] = "Прочность противника",
        ["CyberDefense_ShieldDisplay"] = "Щит: {0} / {1}",
        ["CyberDefense_HpDisplay"] = "ОЗ: {0} / {1}",
        ["CyberDefense_Opponent_GlitchDrone"] = "Глитч-дрон",
        ["CyberDefense_Opponent_VirusCore"] = "Ядро вируса",
        ["CyberDefense_Opponent_CrystalMalware"] = "Кристальный червь",
        ["CyberDefense_Header_Subtitle"] = "ПРАКТИКА > ПРОГРЕСС > СИЛА РАЗУМА",
        ["CyberDefense_WaveDisplay"] = "ВОЛНА {0} / {1}",
        ["CyberDefense_YourShield"] = "ВАШ ЩИТ",
        ["CyberDefense_Integrity"] = "Прочность",
        ["CyberDefense_SolveToAttack"] = "РЕШИТЕ ДЛЯ АТАКИ",
        ["CyberDefense_OperationsTitle"] = "ОПЕРАЦИИ",
        ["CyberDefense_Telemetry_Solve"] = "РЕШАЙТЕ ЗАДАЧИ",
        ["CyberDefense_Telemetry_Defend"] = "ЗАЩИЩАЙТЕ ПРОГРЕСС",
        ["CyberDefense_Telemetry_Progress"] = "ВАШ ПРОГРЕСС",
        ["CyberDefense_Opponent_GlitchDrone_Desc"] = "Поврежденный дрон, нарушающий работу сети.",
        ["CyberDefense_Opponent_VirusCore_Desc"] = "Вредоносное ядро, поражающее буферы вычислений.",
        ["CyberDefense_Opponent_CrystalMalware_Desc"] = "Кристаллический червь, блокирующий числовые потоки.",
        ["CyberDefense_Combo"] = "КОМБО ×{0}",
        ["CyberDefense_ComboAriaLabel"] = "Текущее комбо: {0}",
        ["CyberDefense_Feedback_Hit"] = "-1",
        ["CyberDefense_Feedback_Blocked"] = "ЗАБЛОКИРОВАНО",
        ["CyberDefense_Opponent_DataLeech"] = "Дата-пиявка",
        ["CyberDefense_Opponent_DataLeech_Desc"] = "Сущность, истощающая вычислительные буферы.",
        ["CyberDefense_Opponent_FirewallBreaker"] = "Взломщик фаервола",
        ["CyberDefense_Opponent_FirewallBreaker_Desc"] = "Тяжелобронированная единица, пробивающая системные шлюзы.",
        ["CyberDefense_Opponent_SignalPhantom"] = "Призрак сигнала",
        ["CyberDefense_Opponent_SignalPhantom_Desc"] = "Фазовый стелс-фантом, искажающий частотные каналы.",
        ["CyberDefense_Opponent_QuantumBug"] = "Квантовый баг",
        ["CyberDefense_Opponent_QuantumBug_Desc"] = "Многопоточный квантовый паразит в секторах памяти.",
        ["CyberDefense_Opponent_TrojanWasp"] = "Троянская оса",
        ["CyberDefense_Opponent_TrojanWasp_Desc"] = "Сверхскоростной перехватчик с вредоносным кодом.",
        ["CyberDefense_Opponent_NexusOverlord"] = "Нексус Оверлорд",
        ["CyberDefense_Opponent_NexusOverlord_Desc"] = "Главный титан защиты мейнфрейма с адаптивным щитом.",
        ["CyberDefense_Feedback_CriticalHit"] = "КРИТИЧЕСКИЙ УДАР",
        ["CyberDefense_BossLabel"] = "БОСС",
        ["CyberDefense_BossBattle"] = "БИТВА С БОССОМ"
    };
}
